name: chat_app_dart
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  equatable: ^2.0.2
  flutter_bloc: ^7.0.1
  font_awesome_flutter: ^9.1.0
  formz: ^0.4.0
  pedantic: ^1.11.0
  rive: ^0.7.17
  meta: ^1.3.0
  google_fonts: ^2.1.0
  rxdart: ^0.27.1
  flutter_svg: ^0.22.0
  image_picker: ^0.8.4+4
  authentication_repository:
    path: authentication_repository
  messages_repository:
    path: messages_repository

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile_avatar.jpg


